[package]
name = "pdf-pair"
version = "0.1.2"
description = "Offline dual-pane PDF reader"
authors = ["satopikac <pkumqy@foxmail.com>"]
edition = "2021"
license = "GPL-3.0-only"

[lib]
name = "pdf_pair_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
